import type { SoundType } from './types'

/**
 * Preset/source names as they literally appear in Endlesss's built-in and
 * purchased sound packs (Remix > Packs > Presets), plus the literal
 * "Microphone" label Endlesss gives live mic input — gathered directly from
 * screenshots of the app's own pack browser. A stem parsed from an exported
 * filename (see parseFilename.ts) carries this preset name but has no
 * instrumentMask (that only exists for LORE-sourced stems), so drag-and-drop
 * imports would otherwise default every non-bass/drum stem to 'fx' with no
 * way to recover 'notes' or 'audioIn'. LORE imports use this as a fallback
 * too, for stems whose instrumentMask doesn't resolve to a confident type.
 *
 * Matched as an exact, case-insensitive string against the stem's own name
 * field (see guessSoundTypeFromPresetName) — deliberately not a substring or
 * fuzzy match, since several of these are common English words ("Drop",
 * "Kick", "Wind", "Bee") that would otherwise misclassify a user's own
 * custom-named stem.
 */

const FX_PRESET_NAMES = [
  // Core FX
  'Keymasher',
  'Ripper',
  'Ringmod',
  'Bitcrusher',
  'Degrader',
  'Pitchmod',
  'Multicomb',
  'Freezer',
  'Zap Delay',
  'Dub Delay',
  'Compressor',
  'Lowpass',
  'Highpass',
  'Reverb',
  'Gate',
  'Buzz',
  'GoTo',
  'Saturator',
  'Delay',
  'Comb',
  'Distortion',
  'Smudge',
  'Channel'
]

const NOTES_PRESET_NAMES = [
  // Notes (Core)
  'Eardrop',
  'Cortado',
  'Reveal',
  'Strait',
  'Hopes',
  'Justme',
  'Dreamkiss',
  'Spring',
  'Clunnn',
  'Pianabot',
  'Digisect',
  'Strip',
  // Klang Körper by Echolox
  'Röhrchen',
  'PVC Rohr',
  'Kaputte Röhre',
  'Synthetikrohr',
  'Schüssel',
  'Bronze',
  'Klingel',
  'Stange',
  'Gedämpft',
  'Kleine Flasche',
  'Große Flasche',
  'Im Club',
  // Strange Violin by Echolox
  'Pizzikatto',
  'Suzztain',
  'Owpanstrum',
  'Yuunisun',
  'Schohrty',
  'Aerpluck',
  'Thymestratch',
  'Raezobow',
  'Boudystreik',
  'Wisstly',
  'Admosphear',
  'Skratschy',
  // Spectral Resonance by Echolox
  'Waverest',
  'Swiper',
  'Striker',
  'Cruth',
  'Coins',
  'Grainy',
  'Ice Cube',
  'Ascender',
  'Belluron',
  'Reflector',
  'Oscilloplex',
  'Resodance',
  'Begin',
  'Plane',
  'Waver',
  'Down',
  'Drop',
  'Darpa',
  'Leap',
  'Spire',
  'Sparkle',
  'Kick',
  'Punch',
  'Slap',
  'Protect',
  'Drift',
  'Lift',
  'Reduce',
  'Wait',
  'Approach',
  'Persist',
  'Touch',
  'Breathe',
  'Dream',
  'Listen',
  'Rise',
  'Jaw',
  'Wing',
  'Eye',
  'Sternum',
  'Claw',
  'Nose',
  'Tail',
  'Hoof',
  'Hook',
  'Leash',
  'Knife',
  'Barrier',
  'Christa',
  'D55',
  'Dooo',
  'Fairy Dust',
  'Liedertafel',
  'NHK Harp',
  'Oregon',
  'Oscar',
  'Rosebud',
  'SubClunn',
  'Unicornu',
  'Yellow Nylon',
  'Bali',
  'Boxer',
  'HiLo',
  'Long Bell',
  'Major Perc',
  'Minor Perc',
  'Mello Bell',
  'Shiny',
  'Shots',
  'Marim',
  'Wooden',
  'Xyloh',
  'Angels',
  'Bee Organ',
  'Elfin',
  'Fludde',
  'Kino',
  'Lichen',
  'Mister Gnomer',
  'Piggy',
  'Plaintive',
  'Saphron & Mint',
  'Tuning Fork',
  'Woodsprite',
  'Awake',
  'Ennio',
  'Haunted',
  'Iceman',
  'Jace',
  'Levy',
  'Mansion',
  'Odd Potion',
  'Pagan',
  'Prayer',
  'Tronic',
  'Villa',
  'Celli Flautando',
  'Cello Creak',
  'Cine Choir',
  'Cine Flute',
  'Fury Drone',
  'Piano Grain',
  'Stellar Voices',
  'Keys',
  'Wind',
  'Strings',
  'Plucks',
  'Synth',
  'Almond',
  'Bali Drip',
  'Cassette',
  'Eucalyptus',
  'Leather',
  'Lords Keys',
  'Orange Blip',
  'Orion',
  'Silverlake',
  'Transmute',
  'Willow Mallet',
  'Zipi',
  'Polarsaw',
  'Monolead',
  'Broken',
  'Higher Power',
  'Disaster',
  'Clear',
  'Bee',
  'Scatter',
  'Vaan',
  'Matter',
  'Untuned',
  'Tape',
  'Aprequiema',
  'Flutter',
  'Smashing',
  'Fluzzy',
  'Lifting',
  'Malogre',
  '2pan',
  'Smampsh',
  'Robowah',
  'Glassical',
  'Fanhumm',
  'Swarsh',
  'Balaphonic',
  'BarryPluck',
  'Compost',
  'Doo',
  'Glock',
  'Gnomey',
  'Harmonic',
  'MagicGuitar',
  'Nobleman',
  'OrganCrackle',
  'PianoFrame',
  'Tromper',
  'Sky Boarder',
  'Circuit Dust',
  'Dead Stringer',
  'Kyoto',
  'Drone Zone',
  'Dispersal',
  'Mellower',
  'Organica',
  'Pantastic',
  'Selectaaa',
  'Heaven Sent',
  'Sine Out'
]

const AUDIO_IN_PRESET_NAMES = ['Microphone']

function buildLookup(names: string[], type: SoundType): [string, SoundType][] {
  return names.map((name) => [name.toLowerCase(), type])
}

const PRESET_NAME_TO_TYPE = new Map<string, SoundType>([
  ...buildLookup(FX_PRESET_NAMES, 'fx'),
  ...buildLookup(NOTES_PRESET_NAMES, 'notes'),
  ...buildLookup(AUDIO_IN_PRESET_NAMES, 'audioIn')
])

/** Exact, case-insensitive lookup of a stem's preset/source name against the
 * known-name table above. Returns null (no confident mapping) for anything
 * not in the table, including a user's own custom-named stems. */
export function guessSoundTypeFromPresetName(name: string): SoundType | null {
  return PRESET_NAME_TO_TYPE.get(name.trim().toLowerCase()) ?? null
}
